# Generated by Django 4.2.2 on 2023-07-02 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(default='', max_length=15)),
                ('Last_name', models.CharField(default='', max_length=15)),
                ('Email', models.EmailField(default='', max_length=100)),
                ('Phone', models.CharField(default='', max_length=12)),
                ('Msg', models.TextField(default='', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='PlaceOrder',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('items_json', models.CharField(max_length=5000)),
                ('Name', models.CharField(default='', max_length=15)),
                ('Phone', models.CharField(default='', max_length=15)),
                ('Email', models.EmailField(default='', max_length=100)),
                ('Address', models.CharField(default='', max_length=100)),
                ('City', models.CharField(default='', max_length=12)),
                ('State', models.CharField(default='', max_length=300)),
                ('ZipCode', models.CharField(default='', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_Name', models.CharField(default='', max_length=50)),
                ('Catagory', models.CharField(default='', max_length=50)),
                ('Subcatagory', models.CharField(default='', max_length=50)),
                ('Price', models.IntegerField()),
                ('Description', models.CharField(default='', max_length=1050)),
                ('Publish_date', models.DateField()),
                ('Product_img', models.ImageField(default='', upload_to='shop/images')),
            ],
        ),
    ]
