# Generated by Django 4.2.2 on 2023-07-06 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlideData',
            fields=[
                ('slide_id', models.AutoField(primary_key=True, serialize=False)),
                ('shoe_name_first', models.CharField(max_length=30)),
                ('shoe_name_second', models.CharField(max_length=30)),
                ('shoe_name_third', models.CharField(max_length=30)),
                ('slide_image', models.ImageField(default='', upload_to='shop/MainSlideImage')),
                ('details', models.CharField(max_length=200)),
                ('price', models.IntegerField(max_length=10)),
            ],
        ),
    ]
