# Generated by Django 4.2.2 on 2023-07-06 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0002_slidedata'),
    ]

    operations = [
        migrations.AddField(
            model_name='slidedata',
            name='shoe_company_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='slidedata',
            name='shoe_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='slidedata',
            name='details',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='slidedata',
            name='price',
            field=models.IntegerField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='slidedata',
            name='shoe_name_first',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='slidedata',
            name='shoe_name_second',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='slidedata',
            name='shoe_name_third',
            field=models.CharField(default='', max_length=30),
        ),
    ]
